"""ModelSpec-guided DIY controls for Engineering Lab Visualization Studio.

ModelSpec is declarative guidance only. This panel never executes a ModelSpec's
source/entry function directly. Parameter scans remain restricted to the existing
allow-listed Sweep Executor adapters.
"""
from __future__ import annotations

import json
from typing import Any, Mapping

from physical_lab_model_builder import MODEL_SPEC_SCHEMA, validate_model_spec
from physical_lab_sweep_executor import ADAPTERS, available_adapters, create_sweep_job, start_sweep_job
from physical_lab_visualization_studio import axis_values, build_scan_design, model_spec_guidance, scan_parameter_compatibility


def _numeric_defaults(guidance: Mapping[str, Any]) -> dict[str, float]:
    out: dict[str, float] = {}
    for row in list(guidance.get("parameters") or []):
        if isinstance(row, Mapping) and isinstance(row.get("default"), (int, float)):
            out[str(row.get("name"))] = float(row["default"])
    return out


def _load_spec(uploaded: Any) -> dict[str, Any]:
    if uploaded is None:
        raise ValueError("Select a ModelSpec JSON file first")
    raw = uploaded.getvalue() if hasattr(uploaded, "getvalue") else uploaded.read()
    if len(raw) > 512 * 1024:
        raise ValueError("ModelSpec exceeds the 512 KiB DIY guidance limit")
    value = json.loads(raw.decode("utf-8") if isinstance(raw, (bytes, bytearray)) else str(raw))
    if not isinstance(value, dict):
        raise ValueError("ModelSpec must be a JSON object")
    return validate_model_spec(value)


def _range_defaults(param: Mapping[str, Any]) -> tuple[float, float, float]:
    default = param.get("default")
    lower = param.get("min")
    upper = param.get("max")
    center = float(default) if isinstance(default, (int, float)) else 1.0
    if isinstance(lower, (int, float)) and isinstance(upper, (int, float)) and float(upper) > float(lower):
        return float(lower), float(upper), center
    span = max(abs(center) * 0.25, 1.0)
    return center - span, center + span, center


def render_modelspec_diy(st: Any, profile: str) -> None:
    st.markdown("### ModelSpec · DIY Model Controls")
    st.caption(
        "Use the same physical-lab-model-spec-v1 generated by Research Model Builder to guide parameter selection and visualization hints. "
        "This panel never imports or executes the model source. Execution remains allow-listed through Sweep Executor."
    )
    uploaded = st.file_uploader("ModelSpec / model.json", type=["json"], key=f"pl_modelspec_diy_upload_{profile}")
    if uploaded is None:
        current = st.session_state.get(f"pl_modelspec_guidance_{profile}")
        if current:
            st.info(f"Current Visualization Studio guidance: {current.get('name', 'Research model')}. Upload another model.json to replace it.")
        else:
            st.info("Upload a model.json produced by Research Model Builder to expose its declared parameters, ranges, outputs and visualization hints.")
        return
    try:
        spec = _load_spec(uploaded)
        guidance = model_spec_guidance(spec)
        st.session_state[f"pl_modelspec_guidance_{profile}"] = guidance
    except Exception as exc:
        st.error(f"ModelSpec could not be validated: {exc}")
        return

    c1, c2, c3 = st.columns(3)
    c1.metric("Model", str(guidance.get("name") or "Research model"))
    c2.metric("Parameters", len(guidance.get("parameters") or []))
    c3.metric("Declared outputs", len(guidance.get("outputs") or []))
    if guidance.get("description"):
        st.caption(str(guidance["description"]))
    st.success("ModelSpec guidance is now available to Visualization Studio for non-binding axis and scan suggestions.")

    st.markdown("#### Declared parameter controls")
    params = list(guidance.get("parameters") or [])
    if params:
        st.dataframe(params, hide_index=True, width="stretch")
    else:
        st.info("The ModelSpec declares no named parameters.")

    v1, v2 = st.columns(2)
    with v1:
        st.markdown("#### Declared outputs")
        st.dataframe(list(guidance.get("outputs") or []), hide_index=True, width="stretch")
    with v2:
        st.markdown("#### Visualization hints")
        hints = list(guidance.get("visualizations") or [])
        if hints:
            st.json(hints)
        else:
            st.caption("No visualization hints were declared. Visualization Studio can still discover numeric result fields dynamically.")

    adapters = available_adapters(profile)
    if not adapters:
        st.warning("This Engineering Lab profile has no registered Sweep Executor adapter, so ModelSpec can guide visualization but cannot launch a scan here.")
        st.caption(str(guidance.get("boundary") or ""))
        return

    st.markdown("#### Safe adapter compatibility")
    adapter_ids = [a["id"] for a in adapters]
    labels = {a["id"]: a["label"] for a in adapters}
    adapter = st.selectbox("Allow-listed execution adapter", adapter_ids, format_func=lambda x: labels.get(x, x), key=f"pl_modelspec_diy_adapter_{profile}")
    adapter_spec = ADAPTERS.get(adapter) or {}
    try:
        import importlib, inspect
        module = importlib.import_module(str(adapter_spec.get("module") or ""))
        function = getattr(module, str(adapter_spec.get("function") or ""))
        signature = inspect.signature(function)
        accepted = [name for name, p in signature.parameters.items() if p.kind not in {inspect.Parameter.POSITIONAL_ONLY, inspect.Parameter.VAR_POSITIONAL, inspect.Parameter.VAR_KEYWORD}]
    except Exception as exc:
        st.error(f"Could not inspect registered adapter: {exc}")
        return
    compatibility = scan_parameter_compatibility(guidance, accepted)
    st.dataframe(compatibility, hide_index=True, width="stretch")
    compatible = [row for row in compatibility if row.get("adapter_compatible") and row.get("control") in {"slider", "number"}]
    if not compatible:
        st.warning("No numeric ModelSpec parameter maps to this adapter. The model description remains usable for visualization guidance, but scan execution is disabled.")
        return

    st.markdown("#### ModelSpec-guided scan")
    names = [str(row["name"]) for row in compatible]
    param_a = st.selectbox("Scanned parameter", names, key=f"pl_modelspec_diy_param_{profile}")
    selected = next(row for row in compatible if row["name"] == param_a)
    st.session_state[f"pl_modelspec_preferred_scan_parameter_{profile}"] = param_a
    lo, hi, center = _range_defaults(selected)
    a, b, c, d = st.columns(4)
    start = float(a.number_input("Start", value=lo, key=f"pl_modelspec_diy_start_{profile}"))
    stop = float(b.number_input("Stop", value=hi, key=f"pl_modelspec_diy_stop_{profile}"))
    count = int(c.number_input("Points", min_value=1, max_value=500, value=21, step=1, key=f"pl_modelspec_diy_count_{profile}"))
    spacing = d.selectbox("Spacing", ["linear", "log"], key=f"pl_modelspec_diy_spacing_{profile}")

    fixed = _numeric_defaults(guidance)
    fixed.pop(param_a, None)
    fixed = {name: value for name, value in fixed.items() if name in accepted}
    with st.expander("Fixed defaults mapped from ModelSpec", expanded=False):
        st.json(fixed)
    try:
        values = axis_values(start, stop, count, spacing)
        design = build_scan_design(parameter_a=param_a, values_a=values, fixed=fixed)
        st.dataframe(design[:100], hide_index=True, width="stretch")
    except Exception as exc:
        st.warning(f"Scan design is not valid yet: {exc}")
        return

    st.caption(
        "Execution boundary: ModelSpec selected controls and defaults; the registered Sweep Executor adapter remains the only executable path. "
        "ModelSpec source code is not imported by this panel."
    )
    if st.button("Create ModelSpec-guided scan", type="primary", key=f"pl_modelspec_diy_launch_{profile}"):
        try:
            job = create_sweep_job(profile, adapter, design)
            started = start_sweep_job(str(job["id"]))
            st.success(f"Started {started['id']} · {started['point_count']} point(s)")
            st.rerun()
        except Exception as exc:
            st.error(f"Could not start scan: {exc}")


MODEL_SPEC_BOUNDARY = (
    f"Only {MODEL_SPEC_SCHEMA} is accepted. ModelSpec is declarative guidance and never grants arbitrary execution authority."
)
