"""Deep-science extensions for Physical Lab simulation families.

This module adds bounded scientific studies that strengthen model content rather
than evidence/bridge plumbing:

- Kerr: distant-observer vacuum shadow critical curve from spherical photon
  orbit constants of motion.
- Sun/Jupiter/Saturn: fixed-step velocity-Verlet Newtonian comparator against
  the existing adaptive DOP853 baseline.
- Multilayer honeycomb lattice: microcanonical velocity-autocorrelation (VACF)
  and vibrational spectral-density study from a real time-domain trajectory.
- Numerical Error: a multi-mechanism atlas inspired by BetterBoard's independent
  finite-precision experiments, plus analysis of measured nonuniform time
  series without treating the finest measurement as physical truth.

All results are computational evidence with explicit scientific boundaries.
"""
from __future__ import annotations

from dataclasses import replace
from decimal import Decimal, localcontext
import math
from typing import Any, Iterable, Sequence


def _np():
    import numpy as np
    return np


def _finite(value: Any, name: str) -> float:
    out = float(value)
    if not math.isfinite(out):
        raise ValueError(f"{name} must be finite")
    return out


def _plain(value: Any) -> Any:
    np = _np()
    if value is None or isinstance(value, (str, int, bool)):
        return value
    if isinstance(value, float):
        return value if math.isfinite(value) else None
    if isinstance(value, dict):
        return {str(k): _plain(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_plain(v) for v in value]
    if isinstance(value, np.ndarray):
        return [_plain(v) for v in value.tolist()]
    if hasattr(value, "item"):
        try:
            return _plain(value.item())
        except Exception:
            pass
    return value


# ---------------------------------------------------------------------------
# Kerr distant-observer shadow critical curve
# ---------------------------------------------------------------------------

def _kerr_xi_eta(radius: float, spin: float) -> tuple[float, float]:
    r = float(radius)
    a = float(spin)
    if abs(a) < 1e-12 or abs(r - 1.0) < 1e-12:
        return float("nan"), float("nan")
    xi = (r**3 - 3.0 * r**2 + a * a * r + a * a) / (a * (1.0 - r))
    eta = r**3 * (4.0 * a * a - r * (r - 3.0) ** 2) / (a * a * (r - 1.0) ** 2)
    return float(xi), float(eta)


def kerr_shadow_curve(
    *, spin: float = 0.9, observer_inclination_deg: float = 60.0, samples: int = 900
) -> dict[str, Any]:
    """Return the Kerr vacuum shadow critical curve for an asymptotic observer.

    Celestial coordinates use the standard constants-of-motion mapping
      alpha = -xi / sin(theta_o)
      beta^2 = eta + a^2 cos^2(theta_o) - xi^2 cot^2(theta_o).
    The boundary is generated by unstable spherical photon orbits.  This is not
    a radiative-transfer image or an accretion-flow model.
    """
    np = _np()
    a = _finite(spin, "spin")
    inc = _finite(observer_inclination_deg, "observer inclination")
    if not (0.0 <= abs(a) < 1.0):
        raise ValueError("Kerr shadow requires |a/M| < 1")
    if not (0.5 <= inc <= 90.0):
        raise ValueError("observer inclination must be in [0.5, 90] degrees")
    count = max(180, min(int(samples), 4000))
    theta = math.radians(inc)
    if abs(a) < 1e-10:
        radius = math.sqrt(27.0)
        angles = np.linspace(0.0, 2.0 * math.pi, count, endpoint=True)
        alpha = radius * np.cos(angles)
        beta = radius * np.sin(angles)
        source_r = np.full(alpha.shape, 3.0)
    else:
        horizon = 1.0 + math.sqrt(1.0 - a * a)
        # All physical Kerr spherical photon radii lie inside this bounded scan.
        radii = np.linspace(horizon + 1e-5, 6.0, max(4 * count, 1600))
        upper: list[tuple[float, float, float]] = []
        sin_t = math.sin(theta)
        cos_t = math.cos(theta)
        cot2 = (cos_t / sin_t) ** 2
        for r in radii:
            xi, eta = _kerr_xi_eta(float(r), a)
            if not (math.isfinite(xi) and math.isfinite(eta)):
                continue
            beta2 = eta + a * a * cos_t * cos_t - xi * xi * cot2
            if beta2 < -1e-10:
                continue
            beta_value = math.sqrt(max(beta2, 0.0))
            upper.append((-xi / sin_t, beta_value, float(r)))
        if len(upper) < 30:
            raise RuntimeError("Kerr shadow scan did not resolve enough physical critical-curve points")
        # Order by image-plane alpha so the polygon closes deterministically.
        upper.sort(key=lambda row: row[0])
        # Bound payload size while preserving endpoints.
        if len(upper) > count:
            idx = np.linspace(0, len(upper) - 1, count).round().astype(int)
            upper = [upper[int(i)] for i in idx]
        lower = [(x, -y, r) for x, y, r in reversed(upper)]
        closed = upper + lower + [upper[0]]
        alpha = np.asarray([row[0] for row in closed], dtype=float)
        beta = np.asarray([row[1] for row in closed], dtype=float)
        source_r = np.asarray([row[2] for row in closed], dtype=float)

    alpha_min = float(np.min(alpha)); alpha_max = float(np.max(alpha))
    beta_min = float(np.min(beta)); beta_max = float(np.max(beta))
    area = 0.5 * abs(float(np.dot(alpha[:-1], beta[1:]) - np.dot(beta[:-1], alpha[1:])))
    if alpha[0] != alpha[-1] or beta[0] != beta[-1]:
        area += 0.5 * abs(float(alpha[-1] * beta[0] - beta[-1] * alpha[0]))
    centroid_shift = 0.5 * (alpha_min + alpha_max)
    return _plain({
        "schema": "physical-lab-kerr-shadow-v1",
        "spin_a_over_M": a,
        "observer_inclination_deg": inc,
        "alpha_over_M": alpha,
        "beta_over_M": beta,
        "spherical_photon_radius_over_M": source_r,
        "width_over_M": alpha_max - alpha_min,
        "height_over_M": beta_max - beta_min,
        "horizontal_midpoint_shift_over_M": centroid_shift,
        "critical_curve_area_over_M2": area,
        "alpha_extent_over_M": [alpha_min, alpha_max],
        "beta_extent_over_M": [beta_min, beta_max],
        "boundary": (
            "Asymptotic distant-observer critical curve in vacuum Kerr spacetime. "
            "It is the capture/escape boundary generated by unstable spherical photon orbits; "
            "it is not a synthetic telescope image and contains no emissivity, plasma, absorption, scattering, or instrument response."
        ),
    })


# ---------------------------------------------------------------------------
# Sun/Jupiter/Saturn symplectic long-time comparator
# ---------------------------------------------------------------------------

def _solar_energy(r: Any, v: Any, masses: Any, gravitational_constant: float) -> float:
    np = _np()
    rr = np.asarray(r, dtype=float); vv = np.asarray(v, dtype=float); m = np.asarray(masses, dtype=float)
    kinetic = 0.5 * float(np.sum(m[:, None] * vv * vv))
    potential = 0.0
    for i in range(len(m)):
        for j in range(i + 1, len(m)):
            if m[i] == 0.0 or m[j] == 0.0:
                continue
            potential -= gravitational_constant * float(m[i] * m[j]) / max(float(np.linalg.norm(rr[i] - rr[j])), 1e-15)
    return kinetic + potential


def _solar_ang_momentum(r: Any, v: Any, masses: Any):
    np = _np()
    return np.sum(np.asarray(masses)[:, None] * np.cross(r, v), axis=0)


def solar_symplectic_comparison(
    *, duration_years: float = 40.0, dt_years: float = 0.01,
    inclination_jupiter_deg: float = 10.0, reference_samples: int = 1000,
) -> dict[str, Any]:
    """Compare pure-Newtonian velocity-Verlet with the existing DOP853 solver."""
    np = _np()
    import physical_lab_solar_system_dynamics as solar

    duration = _finite(duration_years, "duration_years")
    dt = _finite(dt_years, "dt_years")
    if not (1.0 <= duration <= 300.0):
        raise ValueError("duration_years must be in [1, 300]")
    if not (0.001 <= dt <= 0.08):
        raise ValueError("dt_years must be in [0.001, 0.08]")
    config = solar.SolarSystemConfig(
        duration_years=duration,
        samples=max(200, min(int(reference_samples), 5000)),
        inclination_jupiter_deg=float(inclination_jupiter_deg),
        saturn_backreaction=True,
        solar_1pn=False,
        velocity_cross=False,
        radial_drag=False,
        rtol=1e-11,
        atol=1e-13,
        max_step_years=min(0.03, max(dt, 0.005)),
    )
    m = solar.masses(config)
    state0 = solar.initial_state(config)
    r, v = solar._unpack(state0)
    r = np.asarray(r, dtype=float).copy(); v = np.asarray(v, dtype=float).copy()
    steps = int(round(duration / dt))
    dt = duration / steps
    stride = max(1, steps // 1600)
    a = solar.acceleration(r, v, config)
    e0 = _solar_energy(r, v, m, solar.G)
    l0 = _solar_ang_momentum(r, v, m)
    mtotal = float(np.sum(m))
    bary0 = np.sum(m[:, None] * r, axis=0) / mtotal
    times: list[float] = [0.0]
    energy_error: list[float] = [0.0]
    j_radius: list[float] = [float(np.linalg.norm(r[1] - r[0]))]
    s_radius: list[float] = [float(np.linalg.norm(r[2] - r[0]))]
    max_energy = 0.0; max_l = 0.0; max_bary = 0.0
    for step in range(1, steps + 1):
        v_half = v + 0.5 * dt * a
        r = r + dt * v_half
        # Pure Newtonian acceleration is velocity independent. Pass v_half only to the shared API.
        a_new = solar.acceleration(r, v_half, config)
        v = v_half + 0.5 * dt * a_new
        a = a_new
        if step % stride == 0 or step == steps:
            energy = _solar_energy(r, v, m, solar.G)
            rel_e = abs(energy - e0) / max(abs(e0), 1e-30)
            l = _solar_ang_momentum(r, v, m)
            rel_l = float(np.linalg.norm(l - l0)) / max(float(np.linalg.norm(l0)), 1e-30)
            bary = np.sum(m[:, None] * r, axis=0) / mtotal
            bary_drift = float(np.linalg.norm(bary - bary0))
            max_energy = max(max_energy, rel_e); max_l = max(max_l, rel_l); max_bary = max(max_bary, bary_drift)
            times.append(step * dt); energy_error.append(rel_e)
            j_radius.append(float(np.linalg.norm(r[1] - r[0])))
            s_radius.append(float(np.linalg.norm(r[2] - r[0])))

    reference = solar.integrate_case(config)
    ref_r = np.asarray(reference["positions_AU"][-1], dtype=float)
    j_final_difference = float(np.linalg.norm((r[1] - r[0]) - (ref_r[1] - ref_r[0])))
    s_final_difference = float(np.linalg.norm((r[2] - r[0]) - (ref_r[2] - ref_r[0])))
    ref_diag = reference.get("diagnostics") or {}
    return _plain({
        "schema": "physical-lab-solar-symplectic-comparison-v1",
        "duration_years": duration,
        "verlet_dt_years": dt,
        "verlet_steps": steps,
        "time_years": times,
        "verlet_relative_energy_error": energy_error,
        "jupiter_heliocentric_radius_AU": j_radius,
        "saturn_heliocentric_radius_AU": s_radius,
        "verlet_max_relative_energy_drift": max_energy,
        "verlet_max_relative_angular_momentum_drift": max_l,
        "verlet_max_barycenter_drift_AU": max_bary,
        "final_jupiter_position_difference_vs_DOP853_AU": j_final_difference,
        "final_saturn_position_difference_vs_DOP853_AU": s_final_difference,
        "dop853_relative_energy_drift": ref_diag.get("relative_energy_drift"),
        "dop853_relative_angular_momentum_drift": ref_diag.get("relative_angular_momentum_drift"),
        "boundary": (
            "Pure point-mass Newtonian Sun/Jupiter/Saturn comparison. Velocity-Verlet is used as an independent fixed-step symplectic-style long-time comparator; "
            "DOP853 remains the adaptive reference implementation. This does not establish ephemeris accuracy, full relativistic dynamics, or observational validation."
        ),
    })


# ---------------------------------------------------------------------------
# Honeycomb VACF / vibrational spectral density
# ---------------------------------------------------------------------------

def lattice_vacf_study(
    *, nx: int = 3, ny: int = 3, layers: int = 2, steps: int = 2048,
    dt: float = 0.004, velocity_scale: float = 0.03, seed: int = 20260911,
    stacking: str = "ABA",
) -> dict[str, Any]:
    """Generate a conservative trajectory, VACF, and finite-cell velocity spectrum."""
    np = _np()
    import physical_lab_lattice_dynamics as lattice

    n_steps = max(256, min(int(steps), 8192))
    h = _finite(dt, "dt")
    scale = _finite(velocity_scale, "velocity_scale")
    if not (0.0005 <= h <= 0.02):
        raise ValueError("dt must be in [0.0005, 0.02]")
    if not (0.0 < scale <= 0.25):
        raise ValueError("velocity_scale must be in (0, 0.25]")
    cfg = lattice.LatticeConfig(
        nx=int(nx), ny=int(ny), layers=int(layers), stacking=str(stacking),
        damping=0.0, interlayer_damping=0.0, drive_mode="none", drive_amplitude=0.0,
        stochastic_mode=False, temperature_reduced=0.0, initial_displacement=0.0,
        duration=max(1.0, n_steps * h), samples=max(256, min(n_steps, 20000)), max_step=h,
    )
    model = lattice.build_lattice(cfg)
    n = len(model.positions)
    u = np.zeros((n, 2), dtype=float)
    rng = np.random.default_rng(int(seed))
    v = rng.normal(scale=scale, size=(n, 2))
    # Remove total translational mode to prevent the VACF from being dominated by rigid drift.
    total_mass = float(np.sum(model.masses))
    com_v = np.sum(model.masses[:, None] * v, axis=0) / total_mass
    v -= com_v

    def conservative_force(uu: Any, vv: Any) -> Any:
        return lattice.force_components(
            model, uu, vv, 0.0, include_dissipation=False, include_external=False
        )["total"]

    force = conservative_force(u, v)
    a = force / model.masses[:, None]
    velocities = np.empty((n_steps, n, 2), dtype=float)
    e0 = lattice.potential_energy(model, u) + 0.5 * float(np.sum(model.masses[:, None] * v * v))
    max_energy_drift = 0.0
    energy_trace: list[float] = []
    energy_time: list[float] = []
    energy_stride = max(1, n_steps // 300)
    for index in range(n_steps):
        v_half = v + 0.5 * h * a
        u = u + h * v_half
        force_new = conservative_force(u, v_half)
        a_new = force_new / model.masses[:, None]
        v = v_half + 0.5 * h * a_new
        a = a_new
        velocities[index] = v
        if index % energy_stride == 0 or index == n_steps - 1:
            energy = lattice.potential_energy(model, u) + 0.5 * float(np.sum(model.masses[:, None] * v * v))
            rel = abs(energy - e0) / max(abs(e0), 1e-30)
            max_energy_drift = max(max_energy_drift, rel)
            energy_trace.append(rel); energy_time.append((index + 1) * h)

    series = velocities.reshape(n_steps, -1)
    # Remove each finite trajectory's temporal mean before correlation/spectral estimation.
    series = series - np.mean(series, axis=0, keepdims=True)
    nfft = 1
    while nfft < 2 * n_steps:
        nfft *= 2
    transformed = np.fft.rfft(series, n=nfft, axis=0)
    corr = np.fft.irfft(transformed * np.conjugate(transformed), n=nfft, axis=0)[:n_steps]
    normalization = np.arange(n_steps, 0, -1, dtype=float)[:, None]
    corr = corr / normalization
    vacf = np.mean(corr, axis=1)
    if abs(float(vacf[0])) <= 1e-30:
        raise RuntimeError("zero VACF normalization")
    vacf_norm = vacf / float(vacf[0])

    window = np.hanning(n_steps)[:, None]
    spectrum_complex = np.fft.rfft(series * window, axis=0)
    density = np.mean(np.abs(spectrum_complex) ** 2, axis=1)
    frequencies = np.fft.rfftfreq(n_steps, d=h)
    if density.size:
        density[0] = 0.0
    area = float(np.trapezoid(density, frequencies)) if len(frequencies) > 1 else 0.0
    density_norm = density / area if area > 0 else density
    dominant_index = int(np.argmax(density_norm[1:]) + 1) if density_norm.size > 1 else 0
    zero_cross = None
    signs = np.signbit(vacf_norm)
    changes = np.where(signs[1:] != signs[:-1])[0]
    if changes.size:
        zero_cross = float((changes[0] + 1) * h)
    return _plain({
        "schema": "physical-lab-lattice-vacf-v1",
        "config": {"nx": int(nx), "ny": int(ny), "layers": int(layers), "stacking": str(stacking), "steps": n_steps, "dt": h, "velocity_scale": scale, "seed": int(seed)},
        "lag_time_reduced": np.arange(n_steps, dtype=float) * h,
        "vacf_normalized": vacf_norm,
        "frequency_cycles_per_reduced_time": frequencies,
        "vibrational_spectral_density_normalized": density_norm,
        "dominant_frequency_cycles_per_reduced_time": float(frequencies[dominant_index]),
        "vacf_first_zero_time_reduced": zero_cross,
        "max_relative_energy_drift": max_energy_drift,
        "energy_trace_time_reduced": energy_time,
        "relative_energy_error_trace": energy_trace,
        "boundary": (
            "Finite-cell reduced-unit conservative trajectory. The VACF and velocity spectral density describe this finite model realization; "
            "they are not q-resolved S(q,omega), not phonon lifetimes, not thermal conductivity, and not calibrated graphene frequencies in THz."
        ),
    })


# ---------------------------------------------------------------------------
# Numerical-error atlas inspired by BetterBoard microbench separation
# ---------------------------------------------------------------------------

def _float32_kahan_sum(value: float, count: int) -> tuple[float, float]:
    np = _np()
    x = np.float32(value)
    naive = np.float32(0.0)
    kahan = np.float32(0.0); compensation = np.float32(0.0)
    for _ in range(int(count)):
        naive = np.float32(naive + x)
        y = np.float32(x - compensation)
        t = np.float32(kahan + y)
        compensation = np.float32((t - kahan) - y)
        kahan = t
    return float(naive), float(kahan)


def numerical_error_atlas() -> dict[str, Any]:
    """Run independent deterministic studies of several numerical error mechanisms."""
    np = _np()

    cancellation_rows = []
    for exponent in range(2, 16):
        for sign in (1.0, -1.0):
            x = sign * (10.0 ** -exponent)
            if 1.0 + x <= 0:
                continue
            raw = math.sqrt(1.0 + x) - 1.0
            stable = x / (math.sqrt(1.0 + x) + 1.0)
            with localcontext() as ctx:
                ctx.prec = 70
                xd = Decimal(str(x))
                ref = float((Decimal(1) + xd).sqrt() - Decimal(1))
            cancellation_rows.append({
                "x": x,
                "raw": raw,
                "stable": stable,
                "reference": ref,
                "raw_abs_error": abs(raw - ref),
                "stable_abs_error": abs(stable - ref),
                "raw_zero": bool(raw == 0.0 and ref != 0.0),
            })

    derivative_rows = []
    x0 = 0.73; exact_derivative = math.cos(x0)
    for exponent in range(1, 14):
        h = 10.0 ** -exponent
        forward = (math.sin(x0 + h) - math.sin(x0)) / h
        central = (math.sin(x0 + h) - math.sin(x0 - h)) / (2.0 * h)
        x32 = np.float32(x0); h32 = np.float32(h)
        plus32 = np.float32(x32 + h32); minus32 = np.float32(x32 - h32)
        collapse_plus = bool(plus32 == x32); collapse_minus = bool(minus32 == x32)
        if not (collapse_plus or collapse_minus):
            central32 = float(np.float32((np.sin(plus32, dtype=np.float32) - np.sin(minus32, dtype=np.float32)) / np.float32(plus32 - minus32)))
        else:
            central32 = None
        derivative_rows.append({
            "h": h,
            "forward_abs_error_float64": abs(forward - exact_derivative),
            "central_abs_error_float64": abs(central - exact_derivative),
            "central_float32": central32,
            "float32_plus_collapsed": collapse_plus,
            "float32_minus_collapsed": collapse_minus,
            "effective_plus_h_float32": float(plus32 - x32),
            "effective_minus_h_float32": float(x32 - minus32),
        })

    integration_rows = []
    ns = [8, 16, 32, 64, 128, 256, 512, 1024]
    errors = []
    for n in ns:
        xx = np.linspace(0.0, math.pi, n + 1)
        estimate = float(np.trapezoid(np.sin(xx), xx))
        error = abs(estimate - 2.0)
        errors.append(error)
        integration_rows.append({"intervals": n, "estimate": estimate, "abs_error": error})
    observed_order = math.log(errors[-2] / errors[-1]) / math.log(2.0)

    summation_rows = []
    increment = float(np.float32(1e-4))
    for count in [100, 1000, 10000, 50000, 100000]:
        naive, kahan = _float32_kahan_sum(increment, count)
        target = increment * count
        summation_rows.append({
            "count": count,
            "binary32_increment": increment,
            "target": target,
            "naive": naive,
            "kahan": kahan,
            "naive_abs_error": abs(naive - target),
            "kahan_abs_error": abs(kahan - target),
        })

    q15_rows = []
    for value in np.linspace(-1.0, 1.0, 41):
        clipped = max(-1.0, min(float(value), (32767.0 / 32768.0)))
        code = int(round(clipped * 32768.0)); code = max(-32768, min(32767, code))
        reconstructed = code / 32768.0
        q15_rows.append({"input": float(value), "code": code, "reconstructed": reconstructed, "abs_error": abs(reconstructed - float(value))})

    overflow_rows = []
    for left, right in [(30000, 10000), (20000, 20000), (-30000, -10000), (32760, 20)]:
        reference = int(left) + int(right)
        wrapped = int(np.asarray(reference, dtype=np.int64).astype(np.int16))
        saturated = max(-32768, min(32767, reference))
        overflow_rows.append({"left": left, "right": right, "widened_reference": reference, "int16_wrapped": wrapped, "int16_saturated": saturated})

    fs = 100.0; signal_frequency = 73.0; sample_count = 1024
    t = np.arange(sample_count) / fs
    signal = np.sin(2.0 * math.pi * signal_frequency * t)
    fft = np.abs(np.fft.rfft(signal * np.hanning(sample_count)))
    freqs = np.fft.rfftfreq(sample_count, d=1.0 / fs)
    peak = int(np.argmax(fft[1:]) + 1)
    observed_alias = float(freqs[peak])
    expected_alias = abs(signal_frequency - round(signal_frequency / fs) * fs)
    expected_alias = min(expected_alias, fs - expected_alias)

    best_central = min(derivative_rows, key=lambda row: row["central_abs_error_float64"])
    smallest_cancel = min(cancellation_rows, key=lambda row: abs(row["x"]))
    final_sum = summation_rows[-1]
    return _plain({
        "schema": "physical-lab-numerical-error-atlas-v1",
        "studies": {
            "catastrophic_cancellation": cancellation_rows,
            "finite_difference_step_size": derivative_rows,
            "trapezoid_convergence": integration_rows,
            "float32_accumulation": summation_rows,
            "q15_quantization": q15_rows,
            "int16_overflow_and_saturation": overflow_rows,
            "aliasing": {"sample_rate_Hz": fs, "signal_frequency_Hz": signal_frequency, "expected_alias_Hz": expected_alias, "observed_fft_peak_Hz": observed_alias},
        },
        "summary": {
            "best_float64_central_h": float(best_central["h"]),
            "best_float64_central_error": float(best_central["central_abs_error_float64"]),
            "float32_step_collapse_cases": sum(1 for row in derivative_rows if row["float32_plus_collapsed"] or row["float32_minus_collapsed"]),
            "trapezoid_observed_order": observed_order,
            "final_naive_sum_abs_error": float(final_sum["naive_abs_error"]),
            "final_kahan_sum_abs_error": float(final_sum["kahan_abs_error"]),
            "smallest_x_raw_cancellation_error": float(smallest_cancel["raw_abs_error"]),
            "smallest_x_stable_cancellation_error": float(smallest_cancel["stable_abs_error"]),
            "alias_frequency_error_Hz": abs(observed_alias - expected_alias),
            "max_q15_abs_error": max(float(row["abs_error"]) for row in q15_rows),
        },
        "boundary": (
            "Independent numerical mechanisms are kept distinct: step-size truncation/roundoff, catastrophic cancellation, accumulation, quantization, overflow/saturation, and aliasing. "
            "A candidate stable algorithm is compared with an independent reference rather than being declared truth by construction."
        ),
    })


def _irregular_three_point_derivative(t0: float, t1: float, t2: float, y0: float, y1: float, y2: float) -> float:
    # Derivative of the degree-2 Lagrange interpolant evaluated at the middle timestamp t1.
    w0 = (t1 - t2) / ((t0 - t1) * (t0 - t2))
    w1 = (2.0 * t1 - t0 - t2) / ((t1 - t0) * (t1 - t2))
    w2 = (t1 - t0) / ((t2 - t0) * (t2 - t1))
    return float(w0 * y0 + w1 * y1 + w2 * y2)


def _trapz_float32(time_values: Any, values: Any, *, kahan: bool) -> float:
    np = _np()
    t = np.asarray(time_values, dtype=np.float32); y = np.asarray(values, dtype=np.float32)
    total = np.float32(0.0); compensation = np.float32(0.0)
    for i in range(len(t) - 1):
        area = np.float32(np.float32(0.5) * np.float32(y[i] + y[i + 1]) * np.float32(t[i + 1] - t[i]))
        if kahan:
            z = np.float32(area - compensation)
            updated = np.float32(total + z)
            compensation = np.float32((updated - total) - z)
            total = updated
        else:
            total = np.float32(total + area)
    return float(total)


def measured_series_numerics(
    time_s: Sequence[float], values: Sequence[float], *, downsample_factors: Iterable[int] = (2, 4, 8, 16)
) -> dict[str, Any]:
    """Analyze acquired samples without treating the finest series as physical truth."""
    np = _np()
    t = np.asarray(time_s, dtype=float); y = np.asarray(values, dtype=float)
    if t.ndim != 1 or y.ndim != 1 or len(t) != len(y) or len(t) < 7:
        raise ValueError("time_s and values must be paired 1D arrays with at least seven samples")
    if not (np.all(np.isfinite(t)) and np.all(np.isfinite(y))):
        raise ValueError("measured series contains non-finite values")
    dt = np.diff(t)
    if np.any(dt <= 0):
        raise ValueError("timestamps must be strictly increasing")
    median_dt = float(np.median(dt)); jitter = dt - median_dt
    full_integral = float(np.trapezoid(y, t))
    float32_naive = _trapz_float32(t, y, kahan=False)
    float32_kahan = _trapz_float32(t, y, kahan=True)
    derivative = np.full(len(t), np.nan, dtype=float)
    for i in range(1, len(t) - 1):
        derivative[i] = _irregular_three_point_derivative(t[i-1], t[i], t[i+1], y[i-1], y[i], y[i+1])
    rows = []
    for raw_factor in downsample_factors:
        factor = max(2, int(raw_factor))
        idx = np.arange(0, len(t), factor, dtype=int)
        if idx[-1] != len(t) - 1:
            idx = np.append(idx, len(t) - 1)
        if len(idx) < 4:
            continue
        tc = t[idx]; yc = y[idx]
        coarse_integral = float(np.trapezoid(yc, tc))
        coarse_derivative = np.asarray([
            _irregular_three_point_derivative(tc[i-1], tc[i], tc[i+1], yc[i-1], yc[i], yc[i+1])
            for i in range(1, len(tc) - 1)
        ])
        reference_derivative = derivative[idx[1:-1]]
        mask = np.isfinite(reference_derivative)
        derivative_rms_change = float(math.sqrt(float(np.mean((coarse_derivative[mask] - reference_derivative[mask]) ** 2)))) if np.any(mask) else None
        rows.append({
            "factor": factor,
            "samples": int(len(idx)),
            "integral": coarse_integral,
            "integral_change_vs_full_series": coarse_integral - full_integral,
            "derivative_rms_change_vs_full_series": derivative_rms_change,
        })
    unique = np.unique(y)
    observed_quantization_step = None
    if len(unique) > 1:
        differences = np.diff(np.sort(unique)); differences = differences[differences > 0]
        if differences.size:
            observed_quantization_step = float(np.min(differences))
    return _plain({
        "schema": "physical-lab-measured-series-numerics-v1",
        "sample_count": int(len(t)),
        "duration_s": float(t[-1] - t[0]),
        "median_dt_s": median_dt,
        "sample_rate_median_Hz": 1.0 / median_dt,
        "jitter_p95_abs_s": float(np.percentile(np.abs(jitter), 95)),
        "jitter_max_abs_s": float(np.max(np.abs(jitter))),
        "observed_min_value_step": observed_quantization_step,
        "float64_trapezoid": full_integral,
        "float32_naive_trapezoid": float32_naive,
        "float32_kahan_trapezoid": float32_kahan,
        "float32_naive_difference_vs_float64": float32_naive - full_integral,
        "float32_kahan_difference_vs_float64": float32_kahan - full_integral,
        "downsampling": rows,
        "time_s": t,
        "irregular_three_point_derivative": derivative,
        "boundary": (
            "The full measured series is an empirical numerical baseline, not exact physical ground truth. "
            "This study separates timestamp irregularity, downsampling, finite-difference sensitivity, accumulation precision, and observed value resolution; physical accuracy still requires calibration/reference evidence."
        ),
    })
